// Generates apps/worker/src/sources/catalog.ts from docs/*.txt slug lists.
// Run: node scripts/gen-catalog.mjs
// Workers have no filesystem access, so slugs must be baked into source.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const docs = (name) =>
  readFileSync(join(root, "docs", name), "utf8")
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter(Boolean);

const greenhouse = docs("greenhouse-slugs.txt");
const lever = docs("lever-slugs.txt");
const smartrecruiters = docs("smartrecruiters-slugs.txt");

const out = `// AUTO-GENERATED by scripts/gen-catalog.mjs — do not edit by hand.
// Regenerate after updating docs/*-slugs.txt.
// Source: ever-jobs/ever-jobs company plugins (extracted 2026-09-07).

export const GREENHOUSE_SLUGS: readonly string[] = ${JSON.stringify(greenhouse)};

export const LEVER_SLUGS: readonly string[] = ${JSON.stringify(lever)};

export const SMARTRECRUITERS_SLUGS: readonly string[] = ${JSON.stringify(smartrecruiters)};
`;

writeFileSync(join(root, "apps", "worker", "src", "sources", "catalog.ts"), out);
console.log(`catalog.ts written: ${greenhouse.length} greenhouse, ${lever.length} lever, ${smartrecruiters.length} smartrecruiters slugs`);
